In [10]:
import numpy as np
import scipy as sp

In [8]:
R = np.random.rand(10,5)
H = R.T @ R

In [18]:
λ, Q, info = sp.linalg.lapack.dsyev(H)
print(info)

0


In [19]:
print(np.linalg.inv(H))

[[ 1.1448995  -0.10278076 -0.46879453 -0.15001808 -0.38663042]
 [-0.10278076  3.87870869  0.52924203 -3.33951527 -1.26758726]
 [-0.46879453  0.52924203  0.83274624 -0.8209932  -0.06493575]
 [-0.15001808 -3.33951527 -0.8209932   3.88671335  0.75058208]
 [-0.38663042 -1.26758726 -0.06493575  0.75058208  1.29646652]]


In [21]:
print(Q @ np.diag(1/λ) @ Q.T)

[[ 1.1448995  -0.10278076 -0.46879453 -0.15001808 -0.38663042]
 [-0.10278076  3.87870869  0.52924203 -3.33951527 -1.26758726]
 [-0.46879453  0.52924203  0.83274624 -0.8209932  -0.06493575]
 [-0.15001808 -3.33951527 -0.8209932   3.88671335  0.75058208]
 [-0.38663042 -1.26758726 -0.06493575  0.75058208  1.29646652]]
