In [2]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{:9.4f}".format(x)})

In [3]:
# matrix multiplication
# A_ij * B_jk = C_jk

# So the loop will do
# C[i,k] = A[i,j] * B[j,k]
# where the sum is being done across index j

A = np.random.rand(5, 3)
B = np.random.randn(3, 4)
C = A @ B

Cman = np.zeros((5,4))

print(C)

for i in range(5):
    for j in range(3):
        for k in range(4):
            Cman[i,k] += A[i,j] * B[j,k]

print(Cman)


[[   0.3867   -1.1814   -0.1948   -0.9559]
 [   0.1348   -0.5035   -0.2549   -0.6569]
 [   0.5477   -1.2108    0.0110   -0.7602]
 [  -0.2153   -0.6099   -0.1084   -0.1933]
 [   0.4809   -1.1896   -0.1009   -0.8806]]
[[   0.3867   -1.1814   -0.1948   -0.9559]
 [   0.1348   -0.5035   -0.2549   -0.6569]
 [   0.5477   -1.2108    0.0110   -0.7602]
 [  -0.2153   -0.6099   -0.1084   -0.1933]
 [   0.4809   -1.1896   -0.1009   -0.8806]]


In [4]:
L = np.tril(np.random.rand(5,5))
print(L)

print("\n")
LtL = L.T @ L
print(LtL)

[[   0.4634    0.0000    0.0000    0.0000    0.0000]
 [   0.5979    0.8943    0.0000    0.0000    0.0000]
 [   0.1903    0.3421    0.7816    0.0000    0.0000]
 [   0.0095    0.4355    0.8805    0.6909    0.0000]
 [   0.4019    0.9426    0.4743    0.4696    0.7899]]


[[   0.7701    0.9828    0.3477    0.1953    0.3175]
 [   0.9828    1.9948    1.0979    0.7435    0.7445]
 [   0.3477    1.0979    1.6112    0.8311    0.3746]
 [   0.1953    0.7435    0.8311    0.6979    0.3710]
 [   0.3175    0.7445    0.3746    0.3710    0.6239]]


In [5]:
# now doing it manually
LtLman = np.zeros((5,5))

for i in range(5):
    for j in range(5):
        if (i > j):
            kinit = i
        else:
            kinit = j
        for k in range(kinit, 5):
            LtLman[i,j] += L[k,i] * L[k,j]

print(LtLman)

[[   0.7701    0.9828    0.3477    0.1953    0.3175]
 [   0.9828    1.9948    1.0979    0.7435    0.7445]
 [   0.3477    1.0979    1.6112    0.8311    0.3746]
 [   0.1953    0.7435    0.8311    0.6979    0.3710]
 [   0.3175    0.7445    0.3746    0.3710    0.6239]]


In [7]:
np.random.seed(123)
R = np.random.rand(3,7)
A = np.round(R.T @ R + np.eye(7) * 0.001, 5)
b = np.round(np.random.randn(7), 5)

print("A=")
for i in range(7):
    for j in range(7):
        print(f"{A[i,j]:.5f},", end="")
    print("\n", end="")

print("\nb=")
for i in range(7):
    print(f"{b[i]:.5f},", end="")
print("\n", end="")

x = np.linalg.solve(A, b)
print("x=")
for i in range(7):
    print(f"{x[i]:.5f},", end="")
print("\n", end="")

print("Solution with 0.1 damping")

x = np.linalg.solve(A + 0.1 * np.eye(7), b)
print("x=")
for i in range(7):
    print(f"{x[i]:.5f},", end="")
print("\n", end="")



L = np.linalg.cholesky(A)
print("\nCholesky factor, L = ")
for i in range(7):
    for j in range(7):
        print(f"{L[i,j]:10.5f} ", end="")
    print("\n", end="")

Linv = np.linalg.inv(L)
Ainv = Linv.T @ Linv
print("\nInverse of cholesky factor = ")
for i in range(7):
    for j in range(7):
        print(f"{Linv[i,j]:10.5f} ", end="")
    print("\n", end="")

Ainv_direct = np.linalg.inv(A)
# compute matrix inverse
print("\nDirect inverse of A = ")
for i in range(7):
    for j in range(7):
        print(f"{Ainv_direct[i,j]:10.5f} ", end="")
    print("\n", end="")


Ainv_direct = np.linalg.inv(A)
# compute matrix inverse
print("\nInverse from cholesky factor = ")
for i in range(7):
    for j in range(7):
        print(f"{Ainv[i,j]:10.5f} ", end="")
    print("\n", end="")

A=
1.11350,0.82240,0.49917,0.68883,1.21194,0.80672,0.97646,
0.82240,0.85881,0.38817,0.45228,0.94877,0.72448,0.77752,
0.49917,0.38817,0.23952,0.29165,0.54609,0.36501,0.36166,
0.68883,0.45228,0.29165,0.45350,0.74011,0.47708,0.67250,
1.21194,0.94877,0.54609,0.74011,1.33270,0.90685,1.08635,
0.80672,0.72448,0.36501,0.47708,0.90685,0.65521,0.77853,
0.97646,0.77752,0.36166,0.67250,1.08635,0.77853,1.36892,

b=
0.46564,0.72492,1.49583,0.74658,-1.10099,-1.41030,-0.74765,
x=
295.51197,920.80226,1282.95627,741.37649,-1175.92570,-1270.41593,218.20756,
Solution with 0.1 damping
x=
3.81345,8.68410,13.28734,7.74585,-11.14577,-12.77690,0.55649,

Cholesky factor, L = 
   1.05523    0.00000    0.00000    0.00000    0.00000    0.00000    0.00000 
   0.77936    0.50141    0.00000    0.00000    0.00000    0.00000    0.00000 
   0.47305    0.03888    0.11931    0.00000    0.00000    0.00000    0.00000 
   0.65278   -0.11262   -0.10699    0.05698    0.00000    0.00000    0.00000 
   1.14851    0.10703   -0.01

In [15]:
H = np.array(
    [
        [
            446.1472,
            1.1578,
            -0.2482,
            -0.0011,
            0.0030,
        ],
        [
            1.1578,
            451.5457,
            25.6279,
            0.0023,
            -0.0072,
        ],
        [
            -0.2482,
            25.6279,
            2141.2285,
            5.6721,
            29.5540,
        ],
        [
            -0.0011,
            0.0023,
            5.6721,
            0.0282,
            0.0699,
        ],
        [
            0.0030,
            -0.0072,
            29.5540,
            0.0699,
            1.4919,
        ],
    ]
)

In [19]:
for i in range(5):
    for j in range(5):
        print(f"{H[i,j]:10.5f}, ", end="")
    print("\n", end="")

 446.14720,    1.15780,   -0.24820,   -0.00110,    0.00300, 
   1.15780,  451.54570,   25.62790,    0.00230,   -0.00720, 
  -0.24820,   25.62790, 2141.22850,    5.67210,   29.55400, 
  -0.00110,    0.00230,    5.67210,    0.02820,    0.06990, 
   0.00300,   -0.00720,   29.55400,    0.06990,    1.49190, 


In [20]:
np.linalg.cholesky(H)

array([[  21.1222,    0.0000,    0.0000,    0.0000,    0.0000],
       [   0.0548,   21.2495,    0.0000,    0.0000,    0.0000],
       [  -0.0118,    1.2061,   46.2577,    0.0000,    0.0000],
       [  -0.0001,    0.0001,    0.1226,    0.1147,    0.0000],
       [   0.0001,   -0.0003,    0.6389,   -0.0736,    1.0384]])

In [21]:
np.linalg.inv(H)

array([[   0.0022,   -0.0000,    0.0000,    0.0000,   -0.0000],
       [  -0.0000,    0.0022,   -0.0001,    0.0116,    0.0008],
       [   0.0000,   -0.0001,    0.0012,   -0.2106,   -0.0144],
       [   0.0000,    0.0116,   -0.2106,   76.3396,    0.5946],
       [  -0.0000,    0.0008,   -0.0144,    0.5946,    0.9274]])